version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: "daily"
    target-branch: "dev"
    assignees:
      - dadyarri
    commit-message:
      prefix: 'build(deps): '
    labels:
      - 'scope: dependencies'
