version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: "daily"
    allow: "all"
    assignees:
      - dadyarri
    commit-message:
      prefix: 'build(deps): '
    labels:
      - dependencies
