version: "3.7"
services:
  db:
    image: postgres
    networks:
      - default
      - my-net
    volumes:
      - pg_data:/var/lib/postgres/data
  bot:
    build: .
    env_file: .env
    command: python /code/jacob/main.py
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - default
      - my-net

networks:
  my-net:

volumes:
  pg_data:
