version: "3.7"

services:

  db:
    container_name: postgres
    image: postgres
    env_file: .env
    restart: always
    volumes:
      - db_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=jacob
      - POSTGRES_PASSWORD=mjro10011
      - POSTGRES_USER=dadyarri

  redis:
    container_name: redis
    image: redis
    command: bash -c "redis-server --appendonly yes --requirepass mjro10011"
    ports:
    - "6378:6379"
    volumes:
    - ./redis-volume:/data

  bot:
    container_name: jacob
    build: .
    env_file: .env
    command: python /code/jacob/main.py
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: {}
